/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY the meta melos script
import 'dart:convert' show json;

final pubSpec = json.decode(
  '{"name":"yt_cli","version":"2.2.6","description":"A CLI tool for the YouTube Data and Live Streaming APIs.","homepage":"https://github.com/faithoflifedev/yt","repository":"https://github.com/faithoflifedev/yt/tree/main/packages/yt_cli","issue_tracker":"https://github.com/faithoflifedev/yt/issues"}',
);
