name: examples
version: 0.0.1
description: Example
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  yt:
    path: ../
