name: yt_cli
version: 2.2.6+5
description: A CLI tool for the YouTube Data, Live Streaming, and Analytics APIs.
homepage: https://github.com/cdavis-code/yt
repository: https://github.com/cdavis-code/yt/tree/main/packages/yt_cli
issue_tracker: https://github.com/cdavis-code/yt/issues

topics:
  - youtube
  - cli
  - api
  - live-streaming
  - oauth2

funding:
  - https://www.buymeacoffee.com/cdavis

resolution: workspace

environment:
  sdk: ^3.8.0

executables:
  yt: yt

dependencies:
  yt: ^2.2.6+5
  args: ^2.7.0
  dio: ^5.9.2
  loggy: ^2.0.3
  oauth2: ^2.0.5
  universal_io: ^2.3.1

dev_dependencies:
  lints: ^6.1.0
