import 'dart:convert';
import 'dart:io';

/// Reads a package's `pubspec.yaml` and generates/updates `lib/meta.dart` with
/// the current name, version, description, homepage, repository, and issue
/// tracker.
///
/// Usage via melos exec (run from each package directory):
///   dart \$MELOS_ROOT_PATH/tool/update_meta.dart
///
/// Manual usage:
///   dart tool/update_meta.dart [package_dir]
///   If omitted, uses the current working directory as the package root.
void main(List<String> args) {
  final packageDir = args.isNotEmpty ? args[0] : '.';
  final dir = Directory(packageDir);

  if (!dir.existsSync()) {
    stderr.writeln('Error: package directory not found: $packageDir');
    exitCode = 1;
    return;
  }

  final pubspecFile = File('${dir.path}/pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found in $packageDir');
    exitCode = 1;
    return;
  }

  final pubspec = pubspecFile.readAsStringSync();

  final name = _extract(pubspec, 'name');
  final version = _extract(pubspec, 'version');
  final description = _extract(pubspec, 'description');
  final homepage = _extract(pubspec, 'homepage');
  final repository = _extract(pubspec, 'repository');
  final issueTracker = _extract(pubspec, 'issue_tracker');

  if (name == null) {
    stderr.writeln('Error: "name" is required in pubspec.yaml');
    exitCode = 1;
    return;
  }

  if (version == null) {
    stderr.writeln('Error: "version" is required in pubspec.yaml');
    exitCode = 1;
    return;
  }

  final fields = <String, String>{
    'name': name,
    'version': version,
    'description': ?description,
    'homepage': ?homepage,
    'repository': ?repository,
    'issue_tracker': ?issueTracker,
  };

  final jsonString = json.encode(fields);

  final metaFile = File('${dir.path}/lib/meta.dart');
  metaFile.writeAsStringSync('''
/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY the meta melos script
import 'dart:convert' show json;

final pubSpec = json.decode(
  '$jsonString',
);
''');

  print('Updated: ${metaFile.path}');
}

/// Extracts the value of a top-level key from a simple YAML file.
String? _extract(String yaml, String key) {
  // Match key: followed by an (optionally quoted) value on the same line.
  // This intentionally does NOT handle multi-line YAML values.
  final regex = RegExp('^$key:\\s*"?(.+?)"?\\s*\$', multiLine: true);
  final match = regex.firstMatch(yaml);
  return match?.group(1)?.replaceAll('"', '');
}
