/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY the meta melos script
import 'dart:convert' show json;

final pubSpec = json.decode(
  '{"name":"yt","version":"3.2.0","description":"Native Dart interface to multiple YouTube REST APIs including the Data and Live Streaming API.","homepage":"https://github.com/cdavis-code/yt_workspace/tree/main/packages/yt","repository":"https://github.com/cdavis-code/yt_workspace","issue_tracker":"https://github.com/cdavis-code/yt_workspace/issues"}',
);
